openapi: 3.0.0
info:
  title: Job Hunt App API
  description: Job Hunt is a job application organizer-tarcker bootstrapped with `create-react-app` on a MERN stack application. This simple API serves to authenticate user and access the Job Hunt app data.
  contact:
    name: Chung Kao
    email: chungckao@gmail.com
  version: "1.0"
servers:
  - url: http://localhost:3001/api/v1
    description: Development local server
  - url: https://ctdjobhuntapp.onrender.com/api/v1
    description: Production server on render.com
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      desctiption: Create user account and return JWT token for accessing user data
      parameters: []
      requestBody:
        description: `username`, `email` and `password` are required
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
            example:
              username: Chung Kao
              email: chungckao@gmail.com
              password: San#3Dragons?
        required: true
      responses:
        "201":
          description: Created - returns an user object and JWT tiken
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterUserResponse"
              example:
                user:
                  username: Chung Kao
                token: jwtToken#$@)345...
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      description: Log user into app and return JWT token for accessing user data
      parameters: []
      requestBody:
        description: `email` and `password` are required
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
            example:
              email: chungckao@gmail.com
              password: San#3Dragons?
        required: true
      responses:
        "200":
          description: OK - returns an user object and JWT token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginUserResponse"
              example:
                user:
                  username: Chung Kao
                token: jwtToken#$@)345...
      deprecated: false
      security: []
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      description: Create a job entry and return a job object
      parameters: []
      requestBody:
        description: `company` and `position` are required
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateJobRequest"
            example:
              company: Zoom
              position: UI Designer
              location: Mountain View, CA
              contact: Mary Alice
              email: maryalice@zoom.com
        required: true
      responses:
        "201":
          description: OK - returns a job object
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateJobResponse"
            example:
              job:
                company: Zoom
                position: UI Designer
                location: Mountain View, CA
                contact: Mary Alice
                email: maryalice@zoom.com
                status: applied
                createdBy: 6331d12dfe32d84c7292132c
                _id: 640ccab1ba64c28c5cbf64b0
                createdAt: 2023-03-11T18:38:41.939Z
                updatedAt: 2023-03-11T18:38:41.939Z
                __v: 0
      deprecated: false
      security:
        - bearer: []
    get:
      tags:
        - Jobs
      summary: Get 10 Jobs
      operationId: Get10Jobs
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number
      responses:
        "200":
          description: OK - returns a jobs object and jobs count
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/Get10JobsResponse"
            example:
              jobs:
                - company: Zoom
                  position: UI Designer
                  location: Mountain View, CA
                  contact: Mary Alice
                  email: maryalice@zoom.com
                  status: applied
                  createdBy: 6331d12dfe32d84c7292132c
                  _id: 640ccab1ba64c28c5cbf64b0
                  createdAt: 2023-03-11T18:38:41.939Z
                  updatedAt: 2023-03-11T18:38:41.939Z
                  __v: 0
                - company: PayPal
                  position: Frontend Engineer
                  location: San Jose, CA
                  contact: John Gannon
                  email: jogngannon@paypal.com
                  status: declined
                  createdBy: 6351d12dfe32d84c7292132c
                  _id: 650ccab1ba64c28c5cbf64b0
                  createdAt: 2023-03-11T18:38:41.939Z
                  updatedAt: 2023-03-11T18:38:41.939Z
                  __v: 0
              count: 2
      deprecated: false
      security:
        - bearer: []
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      parameters:
        - name: id
          in: path
          description: The job ID
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: OK - returns a job object
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetSingleJobResponse"
            example:
              job:
                company: Zoom
                position: UI Designer
                location: Mountain View, CA
                contact: Mary Alice
                email: maryalice@zoom.com
                status: applied
                createdBy: 6331d12dfe32d84c7292132c
                _id: 640ccab1ba64c28c5cbf64b0
                createdAt: 2023-03-11T18:38:41.939Z
                updatedAt: 2023-03-11T18:38:41.939Z
                __v: 0
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters:
        - name: id
          in: path
          description: The job ID
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        description: `company` and `position` are required
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateJobRequest"
            example:
              company: PayPal
              position: Full-stack Engineer
              location: San Jose, CA
              contact: John Gannon
              email: johngannon@paypal.com
              status: interviewed
        required: true
      responses:
        "200":
          description: OK - returns a job object
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateJobResponse"
            example:
              job:
                company: PayPal
                position: Full-stack Engineer
                location: San Jose, CA
                contact: John Gannon
                email: johngannon@paypal.com
                status: interviewed
                createdBy: 6331d12dfe32d84c7292132c
                _id: 640ccab1ba64c28c5cbf64b0
                createdAt: 2023-03-11T18:38:41.939Z
                updatedAt: 2023-03-11T18:38:41.939Z
                __v: 0
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters:
        - name: id
          in: path
          description: The job ID
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: OK - returns a success msg
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteJobResponse"
            example:
              msg: Job ID no. 640ccab1ba64c28c5cbf64b0 has been deleted
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - username
        - email
        - password
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        username: Chung Kao
        email: chungckao@gmail.com
        password: secret#%@
    RegisterUserRresponse:
      title: RegisterUserRresponse
      type: object
      properties:
        user:
          type: object
          properties:
            username:
              type: string
        token:
          type: string
      example:
        user:
          username: Chung Kao
        toekn: jwtToken#$@)345..
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - eamil
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: chungckao@gmail.com
        password: secret#%@
    LoginUserRresponse:
      title: LoginUserRresponse
      type: object
      properties:
        user:
          type: object
          properties:
            username:
              type: string
        token:
          type: string
      example:
        user:
          username: Chung Kao
        toekn: jwtToken#$@)345..
    CreateJobRequest:
      title: CreateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        location:
          type: string
        contact:
          type: string
        email:
          type: string
        status:
          type: string
      example:
        company: Zoom
        position: UI Designer
        location: Mountain View, CA
        contact: Mary Alice
        email: maryalice@zoom.com
        status: applied,
    CreateJobResponse:
      title: CreateJobResponse
      type: object
      properties:
        job:
          type: object
          properties:
            company:
              type: string
            position:
              type: string
            location:
              type: string
            contact:
              type: string
            email:
              type: string
            status:
              type: string
            createdBy:
              type: string
            _id:
              type: string
            createdAt:
              type: string
            updatedAt:
              type: string
            __v:
              type: number
      example:
        job:
          company: Zoom
          position: UI Designer
          location: Mountain View, CA
          contact: Mary Alice
          email: maryalice@zoom.com
          status: applied
          createdBy: 6331d12dfe32d84c7292132c
          _id: 640ccab1ba64c28c5cbf64b0
          createdAt: 2023-03-11T18:38:41.939Z
          updatedAt: 2023-03-11T18:38:41.939Z
          __v: 0
    Get10JobsResponse:
      title: Get10JobsResponse
      type: object
      properties:
        jobs:
          type: array
          items:
            type: object
            properties:
              company:
                type: string
              position:
                type: string
              location:
                type: string
              contact:
                type: string
              email:
                type: string
              status:
                type: string
              createdBy:
                type: string
              _id:
                type: string
              createdAt:
                type: string
              updatedAt:
                type: string
              __v:
                type: number
        count:
          type: number
      example:
        jobs:
          - company: Zoom
            position: UI Designer
            location: Mountain View, CA
            contact: Mary Alice
            email: maryalice@zoom.com
            status: applied
            createdBy: 6331d12dfe32d84c7292132c
            _id: 640ccab1ba64c28c5cbf64b0
            createdAt: 2023-03-11T18:38:41.939Z
            updatedAt: 2023-03-11T18:38:41.939Z
            __v: 0
          - company: PayPal
            position: Frontend Engineer
            location: Mountain View, CA
            contact: John Gannon
            email: jogngannon@paypal.com
            status: declined
            createdBy: 6351d12dfe32d84c7292132c
            _id: 650ccab1ba64c28c5cbf64b0
            createdAt: 2023-03-11T18:38:41.939Z
            updatedAt: 2023-03-11T18:38:41.939Z
            __v: 0
        count: 2
    GetSingleJobResponse:
      title: GetSingleJobResponse
      type: object
      properties:
        job:
          type: object
          properties:
            company:
              type: string
            position:
              type: string
            location:
              type: string
            contact:
              type: string
            email:
              type: string
            status:
              type: string
            createdBy:
              type: string
            _id:
              type: string
            createdAt:
              type: string
            updatedAt:
              type: string
            __v:
              type: number
      example:
        job:
          company: Zoom
          position: UI Designer
          location: Mountain View, CA
          contact: Mary Alice
          email: maryalice@zoom.com
          status: applied
          createdBy: 6331d12dfe32d84c7292132c
          _id: 640ccab1ba64c28c5cbf64b0
          createdAt: 2023-03-11T18:38:41.939Z
          updatedAt: 2023-03-11T18:38:41.939Z
          __v: 0
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        location:
          type: string
        contact:
          type: string
        email:
          type: string
        status:
          type: string
      example:
        company: PayPal
        position: Full-stack Engineer
        location: San Jose, CA
        contact: John Gannon
        email: johngannon@paypal.com
        status: interviewed
    UpdateJobResponse:
      title: UpdateJobResponse
      type: object
      properties:
        job:
          type: object
          properties:
            company:
              type: string
            position:
              type: string
            location:
              type: string
            contact:
              type: string
            email:
              type: string
            status:
              type: string
            createdBy:
              type: string
            _id:
              type: string
            createdAt:
              type: string
            updatedAt:
              type: string
            __v:
              type: number
      example:
        job:
          company: PayPal
          position: Full-stack Engineer
          location: San Jose, CA
          contact: John Gannon
          email: johngannon@paypal.com
          status: interviewed
          createdBy: 6331d12dfe32d84c7292132c
          _id: 640ccab1ba64c28c5cbf64b0
          createdAt: 2023-03-11T18:38:41.939Z
          updatedAt: 2023-03-11T18:38:41.939Z
          __v: 0
    DeleteJobResponse:
      title: DeleteJobResponse
      type: object
      properties:
        msg:
          type: string
      example:
        msg: Job ID no. 640ccab1ba64c28c5cbf64b0 has been deleted
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
    description: User registration and login
  - name: Jobs
    description: CRUD operations on job data
